version: "3.7"

services:
  splunk:
    image: splunk/splunk:${SPLUNK_VERSION}
    container_name: splunk
    hostname: splunk
    ports:
      #- external port:internal port
      - 8000:8000
      - 8088:8088
      - 8089:8089
      - 9997:9997
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_APPS_URL=${SPLUNK_APPS_URL}
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
      - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
    volumes:
      - ./output/${SPLUNK_APP_ID}:/opt/splunk/etc/apps/${SPLUNK_APP_ID}/